# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.29
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This project aims to deal with modules related to manage purchase
    report. You'll find modules that implement various reports related to purchasing
    in general.
repo_name: Purchase Reporting
repo_slug: purchase-reporting
repo_website: https://github.com/OCA/purchase-reporting

